theme: jekyll-theme-cayman
title: Trolling the Gap
description: Tracing the online discussion on Gender Pay Gap through YouTube comments
menu: [
{'name': 'Introduction', 'pagename': 'index'},
{'name': 'Data collection', 'pagename': 'Data Collection'},
{'name': 'Discussion', 'pagename': 'page2'},
{'name': 'Limitations & conclusion', 'pagename': 'page3'},
{'name': 'References', 'pagename': 'page4'},
