theme: jekyll-theme-cayman
title: AfricaRising
description: 
{'name': 'Introduction', 'pagename': 'index'},
{'name': 'Data collection', 'pagename': 'Data Collection'},
{'name': 'Discussion', 'pagename': 'page2'},
{'name': 'Limitations & conclusion', 'pagename': 'page3'},
{'name': 'References', 'pagename': 'page4'},
